/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: cmzw (https://sketchfab.com/cmzw)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/stylized-planet-789725db86f547fc9163b00f302c3e70
title: Stylized planet
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./planet/sceneglb.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-1.54, -0.06, 0]} scale={[1, 1, 1]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials.Clouds}
          />
          <group name="Planet_2">
            <mesh
              geometry={nodes.Object_6.geometry}
              material={materials.Planet}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/sceneglb.glb");
